name: Build and push custom Docker Image

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform of the Image to build for
        required: true
      tag:
        description: Tag for the Image
        required: true
      dockerfile:
        description: Relative path of the Dockerfile to build from
        default: "amd64.Dockerfile"

env:
  TAG: paulhuerkamp/engelsburg-api:${{ github.event.inputs.tag }}
  PLATFORM: ${{ github.event.inputs.platform }}
  DOCKERFILE: ${{ github.event.inputs.dockerfile }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B package
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ env.DOCKERFILE }}
        platforms: ${{ env.PLATFORM }}
        push: true
        tags: ${{ env.TAG }}
