name: Build and push development Docker Image

on:
  push:
    branches: [ "dev" ]

env:
  TAG: paulhuerkamp/engelsburg-api:dev

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B package
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push amd64
      uses: docker/build-push-action@v4
      with:
        context: .
        file: amd64.Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ env.TAG }}-amd64
    - name: Build and push arm64/v8
      uses: docker/build-push-action@v4
      with:
        context: .
        file: arm64.v8.Dockerfile
        platforms: linux/arm64/v8
        push: true
        tags: ${{ env.TAG }}-arm64-v8
